// Generated by gencpp from file project_s_msgs/ObjectManoeuvre.msg
// DO NOT EDIT!


#ifndef PROJECT_S_MSGS_MESSAGE_OBJECTMANOEUVRE_H
#define PROJECT_S_MSGS_MESSAGE_OBJECTMANOEUVRE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/UInt8.h>

namespace project_s_msgs
{
template <class ContainerAllocator>
struct ObjectManoeuvre_
{
  typedef ObjectManoeuvre_<ContainerAllocator> Type;

  ObjectManoeuvre_()
    : header()
    , id()
    , indexOriginLane()
    , objectManoeuvre()
    , objectSignalisation()
    , objectPrediction()
    , objectPredictionProbability()  {
    }
  ObjectManoeuvre_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(_alloc)
    , indexOriginLane(_alloc)
    , objectManoeuvre(_alloc)
    , objectSignalisation(_alloc)
    , objectPrediction(_alloc)
    , objectPredictionProbability(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _id_type;
  _id_type id;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _indexOriginLane_type;
  _indexOriginLane_type indexOriginLane;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _objectManoeuvre_type;
  _objectManoeuvre_type objectManoeuvre;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _objectSignalisation_type;
  _objectSignalisation_type objectSignalisation;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _objectPrediction_type;
  _objectPrediction_type objectPrediction;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _objectPredictionProbability_type;
  _objectPredictionProbability_type objectPredictionProbability;





  typedef boost::shared_ptr< ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectManoeuvre_

typedef ::project_s_msgs::ObjectManoeuvre_<std::allocator<void> > ObjectManoeuvre;

typedef boost::shared_ptr< ::project_s_msgs::ObjectManoeuvre > ObjectManoeuvrePtr;
typedef boost::shared_ptr< ::project_s_msgs::ObjectManoeuvre const> ObjectManoeuvreConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace project_s_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'project_s_msgs': ['/home/segula/Desktop/ava/achitecture_ws/src/project_s_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mobileye_560_660_msgs': ['/home/dev/as_drivers_customer/install/share/mobileye_560_660_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fa042f189b42a91d1a2d603726c850b7";
  }

  static const char* value(const ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfa042f189b42a91dULL;
  static const uint64_t static_value2 = 0x1a2d603726c850b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_s_msgs/ObjectManoeuvre";
  }

  static const char* value(const ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
std_msgs/UInt8 id\n\
\n\
std_msgs/UInt8 indexOriginLane\n\
std_msgs/UInt8 objectManoeuvre\n\
std_msgs/UInt8 objectSignalisation\n\
std_msgs/UInt8 objectPrediction\n\
std_msgs/UInt8 objectPredictionProbability\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/UInt8\n\
uint8 data\n\
";
  }

  static const char* value(const ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.indexOriginLane);
      stream.next(m.objectManoeuvre);
      stream.next(m.objectSignalisation);
      stream.next(m.objectPrediction);
      stream.next(m.objectPredictionProbability);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectManoeuvre_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project_s_msgs::ObjectManoeuvre_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.id);
    s << indent << "indexOriginLane: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.indexOriginLane);
    s << indent << "objectManoeuvre: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.objectManoeuvre);
    s << indent << "objectSignalisation: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.objectSignalisation);
    s << indent << "objectPrediction: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.objectPrediction);
    s << indent << "objectPredictionProbability: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.objectPredictionProbability);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_S_MSGS_MESSAGE_OBJECTMANOEUVRE_H
