// Generated by gencpp from file project_s_msgs/segmentME.msg
// DO NOT EDIT!


#ifndef PROJECT_S_MSGS_MESSAGE_SEGMENTME_H
#define PROJECT_S_MSGS_MESSAGE_SEGMENTME_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project_s_msgs
{
template <class ContainerAllocator>
struct segmentME_
{
  typedef segmentME_<ContainerAllocator> Type;

  segmentME_()
    : NbrSpot(0)
    , offset_debut(0.0)
    , offset_fin(0.0)  {
    }
  segmentME_(const ContainerAllocator& _alloc)
    : NbrSpot(0)
    , offset_debut(0.0)
    , offset_fin(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _NbrSpot_type;
  _NbrSpot_type NbrSpot;

   typedef float _offset_debut_type;
  _offset_debut_type offset_debut;

   typedef float _offset_fin_type;
  _offset_fin_type offset_fin;





  typedef boost::shared_ptr< ::project_s_msgs::segmentME_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project_s_msgs::segmentME_<ContainerAllocator> const> ConstPtr;

}; // struct segmentME_

typedef ::project_s_msgs::segmentME_<std::allocator<void> > segmentME;

typedef boost::shared_ptr< ::project_s_msgs::segmentME > segmentMEPtr;
typedef boost::shared_ptr< ::project_s_msgs::segmentME const> segmentMEConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project_s_msgs::segmentME_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project_s_msgs::segmentME_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace project_s_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'project_s_msgs': ['/home/segula/Desktop/ava/achitecture_ws/src/project_s_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mobileye_560_660_msgs': ['/home/dev/as_drivers_customer/install/share/mobileye_560_660_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::project_s_msgs::segmentME_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_s_msgs::segmentME_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_s_msgs::segmentME_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_s_msgs::segmentME_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_s_msgs::segmentME_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_s_msgs::segmentME_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project_s_msgs::segmentME_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db8cd94b2ab5d013db8e670f53a36229";
  }

  static const char* value(const ::project_s_msgs::segmentME_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb8cd94b2ab5d013ULL;
  static const uint64_t static_value2 = 0xdb8e670f53a36229ULL;
};

template<class ContainerAllocator>
struct DataType< ::project_s_msgs::segmentME_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_s_msgs/segmentME";
  }

  static const char* value(const ::project_s_msgs::segmentME_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project_s_msgs::segmentME_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 NbrSpot\n\
float32 offset_debut\n\
float32 offset_fin\n\
\n\
\n\
";
  }

  static const char* value(const ::project_s_msgs::segmentME_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project_s_msgs::segmentME_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.NbrSpot);
      stream.next(m.offset_debut);
      stream.next(m.offset_fin);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct segmentME_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project_s_msgs::segmentME_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project_s_msgs::segmentME_<ContainerAllocator>& v)
  {
    s << indent << "NbrSpot: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.NbrSpot);
    s << indent << "offset_debut: ";
    Printer<float>::stream(s, indent + "  ", v.offset_debut);
    s << indent << "offset_fin: ";
    Printer<float>::stream(s, indent + "  ", v.offset_fin);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_S_MSGS_MESSAGE_SEGMENTME_H
