// Generated by gencpp from file project_s_msgs/Side.msg
// DO NOT EDIT!


#ifndef PROJECT_S_MSGS_MESSAGE_SIDE_H
#define PROJECT_S_MSGS_MESSAGE_SIDE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <project_s_msgs/Segment.h>

namespace project_s_msgs
{
template <class ContainerAllocator>
struct Side_
{
  typedef Side_<ContainerAllocator> Type;

  Side_()
    : segment()  {
    }
  Side_(const ContainerAllocator& _alloc)
    : segment()  {
  (void)_alloc;
      segment.assign( ::project_s_msgs::Segment_<ContainerAllocator> (_alloc));
  }



   typedef boost::array< ::project_s_msgs::Segment_<ContainerAllocator> , 100>  _segment_type;
  _segment_type segment;





  typedef boost::shared_ptr< ::project_s_msgs::Side_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project_s_msgs::Side_<ContainerAllocator> const> ConstPtr;

}; // struct Side_

typedef ::project_s_msgs::Side_<std::allocator<void> > Side;

typedef boost::shared_ptr< ::project_s_msgs::Side > SidePtr;
typedef boost::shared_ptr< ::project_s_msgs::Side const> SideConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project_s_msgs::Side_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project_s_msgs::Side_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace project_s_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'project_s_msgs': ['/home/segula/Desktop/ava/achitecture_ws/src/project_s_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mobileye_560_660_msgs': ['/home/dev/as_drivers_customer/install/share/mobileye_560_660_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::project_s_msgs::Side_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project_s_msgs::Side_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_s_msgs::Side_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project_s_msgs::Side_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_s_msgs::Side_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project_s_msgs::Side_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project_s_msgs::Side_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cee93af1c46f02386b8de1d0844998c";
  }

  static const char* value(const ::project_s_msgs::Side_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cee93af1c46f023ULL;
  static const uint64_t static_value2 = 0x86b8de1d0844998cULL;
};

template<class ContainerAllocator>
struct DataType< ::project_s_msgs::Side_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_s_msgs/Side";
  }

  static const char* value(const ::project_s_msgs::Side_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project_s_msgs::Side_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project_s_msgs/Segment[100] segment\n\
\n\
================================================================================\n\
MSG: project_s_msgs/Segment\n\
std_msgs/Float32 length		# length of the segment\n\
std_msgs/Float32 angle		# angle of the segment\n\
geometry_msgs/Point position\n\
geometry_msgs/Twist Velocity\n\
\n\
float32 offset\n\
float64 latitude\n\
float64 longitude\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::project_s_msgs::Side_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project_s_msgs::Side_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.segment);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Side_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project_s_msgs::Side_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project_s_msgs::Side_<ContainerAllocator>& v)
  {
    s << indent << "segment[]" << std::endl;
    for (size_t i = 0; i < v.segment.size(); ++i)
    {
      s << indent << "  segment[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::project_s_msgs::Segment_<ContainerAllocator> >::stream(s, indent + "    ", v.segment[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_S_MSGS_MESSAGE_SIDE_H
