(cl:in-package message_project_s-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          OBSTACLEPOSITION-VAL
          OBSTACLEPOSITION
          OBSTACLEVELOCITY-VAL
          OBSTACLEVELOCITY
          OBSTACLEACCELERATION-VAL
          OBSTACLEACCELERATION
          OBSTACLEDIMENSIONS-VAL
          OBSTACLEDIMENSIONS
          OBSTACLEPOSEVARIANCE-VAL
          OBSTACLEPOSEVARIANCE
          OBSTACLEVELOCITYVARIANCE-VAL
          OBSTACLEVELOCITYVARIANCE
          OBSTACLECLASS-VAL
          OBSTACLECLASS
          VISION_ONLY_SIGN_TYPE-VAL
          VISION_ONLY_SIGN_TYPE
))