(cl:defpackage message_project_s-msg
  (:use )
  (:export
   "<EGODATA>"
   "EGODATA"
   "<EGODATAREPORT>"
   "EGODATAREPORT"
   "<GENERICSMARTDATA>"
   "GENERICSMARTDATA"
   "<LANEALIGNMENTME_1>"
   "LANEALIGNMENTME_1"
   "<OBSTACLEALIGNMENT>"
   "OBSTACLEALIGNMENT"
   "<OBSTACLEALIGNMENTREPORT_1>"
   "OBSTACLEALIGNMENTREPORT_1"
   "<OBSTACLEALIGNMENT_1>"
   "OBSTACLEALIGNMENT_1"
   "<TIME>"
   "TIME"
   "<ESRSRR>"
   "ESRSRR"
   "<SYNC>"
   "SYNC"
  ))

