(cl:in-package project_s_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          OFFSET-VAL
          OFFSET
          FUNCTIONROADCLASS-VAL
          FUNCTIONROADCLASS
          WAYFORM-VAL
          WAYFORM
          EFFECTIVESPEEDLIMIT-VAL
          EFFECTIVESPEEDLIMIT
          NBLANESDRIVINGDIRECTION-VAL
          NBLANESDRIVINGDIRECTION
          NBLANESOPPOSITEDIRECTION-VAL
          NBLANESOPPOSITEDIRECTION
))