(cl:in-package project_s_msgs-msg)
(cl:export '(IDLINERIGHT-VAL
          IDLINERIGHT
          IDLINELEFT-VAL
          IDLINELEFT
          OFFSETSTART-VAL
          OFFSETSTART
          OFFSETEND-VAL
          OFFSETEND
          TRAFFICDIRECTION-VAL
          TRAFFICDIRECTION
          PRIORITY-VAL
          PRIORITY
          SPEEDLIMIT-VAL
          SPEEDLIMIT
          TRAFFICSIGN-VAL
          TRAFFICSIGN
          TURNOFFSET-VAL
          TURNOFFSET
          TURNRADIUS-VAL
          TURNRADIUS
          CROSSROADCLASS-VAL
          CROSSROADCLASS
          CROSSROADOFFSET-VAL
          CROSSROADOFFSET
          CROSSROADPRIORITY-VAL
          CROSSROADPRIORITY
))