; Auto-generated. Do not edit!


(cl:in-package project_s_msgs-msg)


;//! \htmlinclude RoutePlanning.msg.html

(cl:defclass <RoutePlanning> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (id
    :reader id
    :initarg :id
    :type std_msgs-msg:UInt8
    :initform (cl:make-instance 'std_msgs-msg:UInt8))
   (roadSegment
    :reader roadSegment
    :initarg :roadSegment
    :type (cl:vector project_s_msgs-msg:Segment)
   :initform (cl:make-array 0 :element-type 'project_s_msgs-msg:Segment :initial-element (cl:make-instance 'project_s_msgs-msg:Segment)))
   (nbrLane
    :reader nbrLane
    :initarg :nbrLane
    :type std_msgs-msg:UInt8
    :initform (cl:make-instance 'std_msgs-msg:UInt8))
   (intersection
    :reader intersection
    :initarg :intersection
    :type std_msgs-msg:UInt8
    :initform (cl:make-instance 'std_msgs-msg:UInt8))
   (list_Links_ID
    :reader list_Links_ID
    :initarg :list_Links_ID
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (list_Links_HEREtile_ID
    :reader list_Links_HEREtile_ID
    :initarg :list_Links_HEREtile_ID
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (list_Nodes_ID
    :reader list_Nodes_ID
    :initarg :list_Nodes_ID
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (list_Nodes_HEREtile_ID
    :reader list_Nodes_HEREtile_ID
    :initarg :list_Nodes_HEREtile_ID
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0))
   (list_Links_vs_Route_direction
    :reader list_Links_vs_Route_direction
    :initarg :list_Links_vs_Route_direction
    :type (cl:vector cl:boolean)
   :initform (cl:make-array 0 :element-type 'cl:boolean :initial-element cl:nil))
   (LIST_LINKS_SIZE
    :reader LIST_LINKS_SIZE
    :initarg :LIST_LINKS_SIZE
    :type cl:integer
    :initform 0)
   (NBRE_POINT_CIRCUIT_GPS
    :reader NBRE_POINT_CIRCUIT_GPS
    :initarg :NBRE_POINT_CIRCUIT_GPS
    :type cl:integer
    :initform 0)
   (NBRE_POINT_TABLEAU_GPS
    :reader NBRE_POINT_TABLEAU_GPS
    :initarg :NBRE_POINT_TABLEAU_GPS
    :type cl:integer
    :initform 0)
   (Tableau_circuit_GPS
    :reader Tableau_circuit_GPS
    :initarg :Tableau_circuit_GPS
    :type (cl:vector project_s_msgs-msg:point_GPS)
   :initform (cl:make-array 0 :element-type 'project_s_msgs-msg:point_GPS :initial-element (cl:make-instance 'project_s_msgs-msg:point_GPS)))
   (Tableau_circuit_GPS_gauche
    :reader Tableau_circuit_GPS_gauche
    :initarg :Tableau_circuit_GPS_gauche
    :type (cl:vector project_s_msgs-msg:point_GPS)
   :initform (cl:make-array 0 :element-type 'project_s_msgs-msg:point_GPS :initial-element (cl:make-instance 'project_s_msgs-msg:point_GPS)))
   (Tableau_circuit_GPS_droite
    :reader Tableau_circuit_GPS_droite
    :initarg :Tableau_circuit_GPS_droite
    :type (cl:vector project_s_msgs-msg:point_GPS)
   :initform (cl:make-array 0 :element-type 'project_s_msgs-msg:point_GPS :initial-element (cl:make-instance 'project_s_msgs-msg:point_GPS)))
   (Tableau_circuit_GPS_MEgauche
    :reader Tableau_circuit_GPS_MEgauche
    :initarg :Tableau_circuit_GPS_MEgauche
    :type (cl:vector project_s_msgs-msg:point_GPS)
   :initform (cl:make-array 0 :element-type 'project_s_msgs-msg:point_GPS :initial-element (cl:make-instance 'project_s_msgs-msg:point_GPS)))
   (Tableau_circuit_GPS_MEdroite
    :reader Tableau_circuit_GPS_MEdroite
    :initarg :Tableau_circuit_GPS_MEdroite
    :type (cl:vector project_s_msgs-msg:point_GPS)
   :initform (cl:make-array 0 :element-type 'project_s_msgs-msg:point_GPS :initial-element (cl:make-instance 'project_s_msgs-msg:point_GPS)))
   (Tableau_circuit_speedlimit
    :reader Tableau_circuit_speedlimit
    :initarg :Tableau_circuit_speedlimit
    :type (cl:vector project_s_msgs-msg:speed_limit)
   :initform (cl:make-array 0 :element-type 'project_s_msgs-msg:speed_limit :initial-element (cl:make-instance 'project_s_msgs-msg:speed_limit)))
   (Tableau_circuit_curvature
    :reader Tableau_circuit_curvature
    :initarg :Tableau_circuit_curvature
    :type (cl:vector project_s_msgs-msg:curvature)
   :initform (cl:make-array 0 :element-type 'project_s_msgs-msg:curvature :initial-element (cl:make-instance 'project_s_msgs-msg:curvature)))
   (Tableau_circuit_trafficsign
    :reader Tableau_circuit_trafficsign
    :initarg :Tableau_circuit_trafficsign
    :type (cl:vector project_s_msgs-msg:traffic_sign)
   :initform (cl:make-array 0 :element-type 'project_s_msgs-msg:traffic_sign :initial-element (cl:make-instance 'project_s_msgs-msg:traffic_sign)))
   (Tableau_circuit_ehSegmentAO
    :reader Tableau_circuit_ehSegmentAO
    :initarg :Tableau_circuit_ehSegmentAO
    :type (cl:vector project_s_msgs-msg:segmentME)
   :initform (cl:make-array 0 :element-type 'project_s_msgs-msg:segmentME :initial-element (cl:make-instance 'project_s_msgs-msg:segmentME)))
   (Tableau_circuit_ehSegmentEO
    :reader Tableau_circuit_ehSegmentEO
    :initarg :Tableau_circuit_ehSegmentEO
    :type (cl:vector project_s_msgs-msg:segmentME)
   :initform (cl:make-array 0 :element-type 'project_s_msgs-msg:segmentME :initial-element (cl:make-instance 'project_s_msgs-msg:segmentME))))
)

(cl:defclass RoutePlanning (<RoutePlanning>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RoutePlanning>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RoutePlanning)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name project_s_msgs-msg:<RoutePlanning> is deprecated: use project_s_msgs-msg:RoutePlanning instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:header-val is deprecated.  Use project_s_msgs-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'id-val :lambda-list '(m))
(cl:defmethod id-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:id-val is deprecated.  Use project_s_msgs-msg:id instead.")
  (id m))

(cl:ensure-generic-function 'roadSegment-val :lambda-list '(m))
(cl:defmethod roadSegment-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:roadSegment-val is deprecated.  Use project_s_msgs-msg:roadSegment instead.")
  (roadSegment m))

(cl:ensure-generic-function 'nbrLane-val :lambda-list '(m))
(cl:defmethod nbrLane-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:nbrLane-val is deprecated.  Use project_s_msgs-msg:nbrLane instead.")
  (nbrLane m))

(cl:ensure-generic-function 'intersection-val :lambda-list '(m))
(cl:defmethod intersection-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:intersection-val is deprecated.  Use project_s_msgs-msg:intersection instead.")
  (intersection m))

(cl:ensure-generic-function 'list_Links_ID-val :lambda-list '(m))
(cl:defmethod list_Links_ID-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:list_Links_ID-val is deprecated.  Use project_s_msgs-msg:list_Links_ID instead.")
  (list_Links_ID m))

(cl:ensure-generic-function 'list_Links_HEREtile_ID-val :lambda-list '(m))
(cl:defmethod list_Links_HEREtile_ID-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:list_Links_HEREtile_ID-val is deprecated.  Use project_s_msgs-msg:list_Links_HEREtile_ID instead.")
  (list_Links_HEREtile_ID m))

(cl:ensure-generic-function 'list_Nodes_ID-val :lambda-list '(m))
(cl:defmethod list_Nodes_ID-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:list_Nodes_ID-val is deprecated.  Use project_s_msgs-msg:list_Nodes_ID instead.")
  (list_Nodes_ID m))

(cl:ensure-generic-function 'list_Nodes_HEREtile_ID-val :lambda-list '(m))
(cl:defmethod list_Nodes_HEREtile_ID-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:list_Nodes_HEREtile_ID-val is deprecated.  Use project_s_msgs-msg:list_Nodes_HEREtile_ID instead.")
  (list_Nodes_HEREtile_ID m))

(cl:ensure-generic-function 'list_Links_vs_Route_direction-val :lambda-list '(m))
(cl:defmethod list_Links_vs_Route_direction-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:list_Links_vs_Route_direction-val is deprecated.  Use project_s_msgs-msg:list_Links_vs_Route_direction instead.")
  (list_Links_vs_Route_direction m))

(cl:ensure-generic-function 'LIST_LINKS_SIZE-val :lambda-list '(m))
(cl:defmethod LIST_LINKS_SIZE-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:LIST_LINKS_SIZE-val is deprecated.  Use project_s_msgs-msg:LIST_LINKS_SIZE instead.")
  (LIST_LINKS_SIZE m))

(cl:ensure-generic-function 'NBRE_POINT_CIRCUIT_GPS-val :lambda-list '(m))
(cl:defmethod NBRE_POINT_CIRCUIT_GPS-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:NBRE_POINT_CIRCUIT_GPS-val is deprecated.  Use project_s_msgs-msg:NBRE_POINT_CIRCUIT_GPS instead.")
  (NBRE_POINT_CIRCUIT_GPS m))

(cl:ensure-generic-function 'NBRE_POINT_TABLEAU_GPS-val :lambda-list '(m))
(cl:defmethod NBRE_POINT_TABLEAU_GPS-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:NBRE_POINT_TABLEAU_GPS-val is deprecated.  Use project_s_msgs-msg:NBRE_POINT_TABLEAU_GPS instead.")
  (NBRE_POINT_TABLEAU_GPS m))

(cl:ensure-generic-function 'Tableau_circuit_GPS-val :lambda-list '(m))
(cl:defmethod Tableau_circuit_GPS-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:Tableau_circuit_GPS-val is deprecated.  Use project_s_msgs-msg:Tableau_circuit_GPS instead.")
  (Tableau_circuit_GPS m))

(cl:ensure-generic-function 'Tableau_circuit_GPS_gauche-val :lambda-list '(m))
(cl:defmethod Tableau_circuit_GPS_gauche-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:Tableau_circuit_GPS_gauche-val is deprecated.  Use project_s_msgs-msg:Tableau_circuit_GPS_gauche instead.")
  (Tableau_circuit_GPS_gauche m))

(cl:ensure-generic-function 'Tableau_circuit_GPS_droite-val :lambda-list '(m))
(cl:defmethod Tableau_circuit_GPS_droite-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:Tableau_circuit_GPS_droite-val is deprecated.  Use project_s_msgs-msg:Tableau_circuit_GPS_droite instead.")
  (Tableau_circuit_GPS_droite m))

(cl:ensure-generic-function 'Tableau_circuit_GPS_MEgauche-val :lambda-list '(m))
(cl:defmethod Tableau_circuit_GPS_MEgauche-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:Tableau_circuit_GPS_MEgauche-val is deprecated.  Use project_s_msgs-msg:Tableau_circuit_GPS_MEgauche instead.")
  (Tableau_circuit_GPS_MEgauche m))

(cl:ensure-generic-function 'Tableau_circuit_GPS_MEdroite-val :lambda-list '(m))
(cl:defmethod Tableau_circuit_GPS_MEdroite-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:Tableau_circuit_GPS_MEdroite-val is deprecated.  Use project_s_msgs-msg:Tableau_circuit_GPS_MEdroite instead.")
  (Tableau_circuit_GPS_MEdroite m))

(cl:ensure-generic-function 'Tableau_circuit_speedlimit-val :lambda-list '(m))
(cl:defmethod Tableau_circuit_speedlimit-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:Tableau_circuit_speedlimit-val is deprecated.  Use project_s_msgs-msg:Tableau_circuit_speedlimit instead.")
  (Tableau_circuit_speedlimit m))

(cl:ensure-generic-function 'Tableau_circuit_curvature-val :lambda-list '(m))
(cl:defmethod Tableau_circuit_curvature-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:Tableau_circuit_curvature-val is deprecated.  Use project_s_msgs-msg:Tableau_circuit_curvature instead.")
  (Tableau_circuit_curvature m))

(cl:ensure-generic-function 'Tableau_circuit_trafficsign-val :lambda-list '(m))
(cl:defmethod Tableau_circuit_trafficsign-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:Tableau_circuit_trafficsign-val is deprecated.  Use project_s_msgs-msg:Tableau_circuit_trafficsign instead.")
  (Tableau_circuit_trafficsign m))

(cl:ensure-generic-function 'Tableau_circuit_ehSegmentAO-val :lambda-list '(m))
(cl:defmethod Tableau_circuit_ehSegmentAO-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:Tableau_circuit_ehSegmentAO-val is deprecated.  Use project_s_msgs-msg:Tableau_circuit_ehSegmentAO instead.")
  (Tableau_circuit_ehSegmentAO m))

(cl:ensure-generic-function 'Tableau_circuit_ehSegmentEO-val :lambda-list '(m))
(cl:defmethod Tableau_circuit_ehSegmentEO-val ((m <RoutePlanning>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader project_s_msgs-msg:Tableau_circuit_ehSegmentEO-val is deprecated.  Use project_s_msgs-msg:Tableau_circuit_ehSegmentEO instead.")
  (Tableau_circuit_ehSegmentEO m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RoutePlanning>) ostream)
  "Serializes a message object of type '<RoutePlanning>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'id) ostream)
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'roadSegment))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'roadSegment))
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'nbrLane) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'intersection) ostream)
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'list_Links_ID))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) ele) ostream))
   (cl:slot-value msg 'list_Links_ID))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'list_Links_HEREtile_ID))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) ele) ostream))
   (cl:slot-value msg 'list_Links_HEREtile_ID))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'list_Nodes_ID))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) ele) ostream))
   (cl:slot-value msg 'list_Nodes_ID))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'list_Nodes_HEREtile_ID))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) ele) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) ele) ostream))
   (cl:slot-value msg 'list_Nodes_HEREtile_ID))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'list_Links_vs_Route_direction))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if ele 1 0)) ostream))
   (cl:slot-value msg 'list_Links_vs_Route_direction))
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'LIST_LINKS_SIZE)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'LIST_LINKS_SIZE)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'LIST_LINKS_SIZE)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'LIST_LINKS_SIZE)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'NBRE_POINT_CIRCUIT_GPS)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'NBRE_POINT_CIRCUIT_GPS)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'NBRE_POINT_CIRCUIT_GPS)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'NBRE_POINT_CIRCUIT_GPS)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'NBRE_POINT_TABLEAU_GPS)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'NBRE_POINT_TABLEAU_GPS)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'NBRE_POINT_TABLEAU_GPS)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'NBRE_POINT_TABLEAU_GPS)) ostream)
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Tableau_circuit_GPS))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'Tableau_circuit_GPS))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Tableau_circuit_GPS_gauche))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'Tableau_circuit_GPS_gauche))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Tableau_circuit_GPS_droite))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'Tableau_circuit_GPS_droite))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Tableau_circuit_GPS_MEgauche))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'Tableau_circuit_GPS_MEgauche))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Tableau_circuit_GPS_MEdroite))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'Tableau_circuit_GPS_MEdroite))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Tableau_circuit_speedlimit))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'Tableau_circuit_speedlimit))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Tableau_circuit_curvature))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'Tableau_circuit_curvature))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Tableau_circuit_trafficsign))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'Tableau_circuit_trafficsign))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Tableau_circuit_ehSegmentAO))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'Tableau_circuit_ehSegmentAO))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'Tableau_circuit_ehSegmentEO))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'Tableau_circuit_ehSegmentEO))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RoutePlanning>) istream)
  "Deserializes a message object of type '<RoutePlanning>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'id) istream)
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'roadSegment) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'roadSegment)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'project_s_msgs-msg:Segment))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'nbrLane) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'intersection) istream)
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'list_Links_ID) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'list_Links_ID)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'list_Links_HEREtile_ID) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'list_Links_HEREtile_ID)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'list_Nodes_ID) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'list_Nodes_ID)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'list_Nodes_HEREtile_ID) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'list_Nodes_HEREtile_ID)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:aref vals i)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:aref vals i)) (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'list_Links_vs_Route_direction) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'list_Links_vs_Route_direction)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:not (cl:zerop (cl:read-byte istream)))))))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'LIST_LINKS_SIZE)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'LIST_LINKS_SIZE)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'LIST_LINKS_SIZE)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'LIST_LINKS_SIZE)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'NBRE_POINT_CIRCUIT_GPS)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'NBRE_POINT_CIRCUIT_GPS)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'NBRE_POINT_CIRCUIT_GPS)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'NBRE_POINT_CIRCUIT_GPS)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'NBRE_POINT_TABLEAU_GPS)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'NBRE_POINT_TABLEAU_GPS)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'NBRE_POINT_TABLEAU_GPS)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'NBRE_POINT_TABLEAU_GPS)) (cl:read-byte istream))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Tableau_circuit_GPS) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Tableau_circuit_GPS)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'project_s_msgs-msg:point_GPS))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Tableau_circuit_GPS_gauche) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Tableau_circuit_GPS_gauche)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'project_s_msgs-msg:point_GPS))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Tableau_circuit_GPS_droite) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Tableau_circuit_GPS_droite)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'project_s_msgs-msg:point_GPS))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Tableau_circuit_GPS_MEgauche) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Tableau_circuit_GPS_MEgauche)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'project_s_msgs-msg:point_GPS))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Tableau_circuit_GPS_MEdroite) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Tableau_circuit_GPS_MEdroite)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'project_s_msgs-msg:point_GPS))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Tableau_circuit_speedlimit) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Tableau_circuit_speedlimit)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'project_s_msgs-msg:speed_limit))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Tableau_circuit_curvature) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Tableau_circuit_curvature)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'project_s_msgs-msg:curvature))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Tableau_circuit_trafficsign) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Tableau_circuit_trafficsign)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'project_s_msgs-msg:traffic_sign))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Tableau_circuit_ehSegmentAO) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Tableau_circuit_ehSegmentAO)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'project_s_msgs-msg:segmentME))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'Tableau_circuit_ehSegmentEO) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'Tableau_circuit_ehSegmentEO)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'project_s_msgs-msg:segmentME))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RoutePlanning>)))
  "Returns string type for a message object of type '<RoutePlanning>"
  "project_s_msgs/RoutePlanning")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RoutePlanning)))
  "Returns string type for a message object of type 'RoutePlanning"
  "project_s_msgs/RoutePlanning")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RoutePlanning>)))
  "Returns md5sum for a message object of type '<RoutePlanning>"
  "686ce86a53e3fc605337589df78e8395")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RoutePlanning)))
  "Returns md5sum for a message object of type 'RoutePlanning"
  "686ce86a53e3fc605337589df78e8395")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RoutePlanning>)))
  "Returns full string definition for message of type '<RoutePlanning>"
  (cl:format cl:nil "Header header~%std_msgs/UInt8 id~%~%project_s_msgs/Segment[] roadSegment		#segments array   ~%std_msgs/UInt8 nbrLane~%std_msgs/UInt8 intersection~%~%uint32[] list_Links_ID~%uint32[] list_Links_HEREtile_ID~%uint32[] list_Nodes_ID~%uint32[] list_Nodes_HEREtile_ID~%bool[] list_Links_vs_Route_direction~%uint32 LIST_LINKS_SIZE~%~%uint32 NBRE_POINT_CIRCUIT_GPS~%uint32 NBRE_POINT_TABLEAU_GPS~%~%project_s_msgs/point_GPS[]   Tableau_circuit_GPS~%project_s_msgs/point_GPS[]   Tableau_circuit_GPS_gauche~%project_s_msgs/point_GPS[]   Tableau_circuit_GPS_droite~%~%project_s_msgs/point_GPS[]   Tableau_circuit_GPS_MEgauche~%project_s_msgs/point_GPS[]   Tableau_circuit_GPS_MEdroite~%~%project_s_msgs/speed_limit[] Tableau_circuit_speedlimit~%project_s_msgs/curvature[]   Tableau_circuit_curvature~%project_s_msgs/traffic_sign[]   Tableau_circuit_trafficsign~%~%~%project_s_msgs/segmentME[] Tableau_circuit_ehSegmentAO~%project_s_msgs/segmentME[] Tableau_circuit_ehSegmentEO~%~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: std_msgs/UInt8~%uint8 data~%~%================================================================================~%MSG: project_s_msgs/Segment~%std_msgs/Float32 length		# length of the segment~%std_msgs/Float32 angle		# angle of the segment~%geometry_msgs/Point position~%geometry_msgs/Twist Velocity~%~%float32 offset~%float64 latitude~%float64 longitude~%~%~%================================================================================~%MSG: std_msgs/Float32~%float32 data~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Twist~%# This expresses velocity in free space broken into its linear and angular parts.~%Vector3  linear~%Vector3  angular~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%================================================================================~%MSG: project_s_msgs/point_GPS~%float64 latitude~%float64 longitude~%float32 offset~%~%~%================================================================================~%MSG: project_s_msgs/speed_limit~%float32 offset~%uint8 effectiveSpeedLimit~%~%~%================================================================================~%MSG: project_s_msgs/curvature~%float32 offset~%float32 value~%~%================================================================================~%MSG: project_s_msgs/traffic_sign~%float32 offset~%uint8 Sign_Type~%uint8 Value~%uint8 Lane~%uint8 Sign_Location~%float64 latitude~%float64 longitude~%~%~%~%~%================================================================================~%MSG: project_s_msgs/segmentME~%uint32 NbrSpot~%float32 offset_debut~%float32 offset_fin~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RoutePlanning)))
  "Returns full string definition for message of type 'RoutePlanning"
  (cl:format cl:nil "Header header~%std_msgs/UInt8 id~%~%project_s_msgs/Segment[] roadSegment		#segments array   ~%std_msgs/UInt8 nbrLane~%std_msgs/UInt8 intersection~%~%uint32[] list_Links_ID~%uint32[] list_Links_HEREtile_ID~%uint32[] list_Nodes_ID~%uint32[] list_Nodes_HEREtile_ID~%bool[] list_Links_vs_Route_direction~%uint32 LIST_LINKS_SIZE~%~%uint32 NBRE_POINT_CIRCUIT_GPS~%uint32 NBRE_POINT_TABLEAU_GPS~%~%project_s_msgs/point_GPS[]   Tableau_circuit_GPS~%project_s_msgs/point_GPS[]   Tableau_circuit_GPS_gauche~%project_s_msgs/point_GPS[]   Tableau_circuit_GPS_droite~%~%project_s_msgs/point_GPS[]   Tableau_circuit_GPS_MEgauche~%project_s_msgs/point_GPS[]   Tableau_circuit_GPS_MEdroite~%~%project_s_msgs/speed_limit[] Tableau_circuit_speedlimit~%project_s_msgs/curvature[]   Tableau_circuit_curvature~%project_s_msgs/traffic_sign[]   Tableau_circuit_trafficsign~%~%~%project_s_msgs/segmentME[] Tableau_circuit_ehSegmentAO~%project_s_msgs/segmentME[] Tableau_circuit_ehSegmentEO~%~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: std_msgs/UInt8~%uint8 data~%~%================================================================================~%MSG: project_s_msgs/Segment~%std_msgs/Float32 length		# length of the segment~%std_msgs/Float32 angle		# angle of the segment~%geometry_msgs/Point position~%geometry_msgs/Twist Velocity~%~%float32 offset~%float64 latitude~%float64 longitude~%~%~%================================================================================~%MSG: std_msgs/Float32~%float32 data~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Twist~%# This expresses velocity in free space broken into its linear and angular parts.~%Vector3  linear~%Vector3  angular~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%================================================================================~%MSG: project_s_msgs/point_GPS~%float64 latitude~%float64 longitude~%float32 offset~%~%~%================================================================================~%MSG: project_s_msgs/speed_limit~%float32 offset~%uint8 effectiveSpeedLimit~%~%~%================================================================================~%MSG: project_s_msgs/curvature~%float32 offset~%float32 value~%~%================================================================================~%MSG: project_s_msgs/traffic_sign~%float32 offset~%uint8 Sign_Type~%uint8 Value~%uint8 Lane~%uint8 Sign_Location~%float64 latitude~%float64 longitude~%~%~%~%~%================================================================================~%MSG: project_s_msgs/segmentME~%uint32 NbrSpot~%float32 offset_debut~%float32 offset_fin~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RoutePlanning>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'id))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'roadSegment) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'nbrLane))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'intersection))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'list_Links_ID) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'list_Links_HEREtile_ID) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'list_Nodes_ID) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'list_Nodes_HEREtile_ID) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'list_Links_vs_Route_direction) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 1)))
     4
     4
     4
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Tableau_circuit_GPS) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Tableau_circuit_GPS_gauche) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Tableau_circuit_GPS_droite) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Tableau_circuit_GPS_MEgauche) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Tableau_circuit_GPS_MEdroite) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Tableau_circuit_speedlimit) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Tableau_circuit_curvature) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Tableau_circuit_trafficsign) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Tableau_circuit_ehSegmentAO) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'Tableau_circuit_ehSegmentEO) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RoutePlanning>))
  "Converts a ROS message object to a list"
  (cl:list 'RoutePlanning
    (cl:cons ':header (header msg))
    (cl:cons ':id (id msg))
    (cl:cons ':roadSegment (roadSegment msg))
    (cl:cons ':nbrLane (nbrLane msg))
    (cl:cons ':intersection (intersection msg))
    (cl:cons ':list_Links_ID (list_Links_ID msg))
    (cl:cons ':list_Links_HEREtile_ID (list_Links_HEREtile_ID msg))
    (cl:cons ':list_Nodes_ID (list_Nodes_ID msg))
    (cl:cons ':list_Nodes_HEREtile_ID (list_Nodes_HEREtile_ID msg))
    (cl:cons ':list_Links_vs_Route_direction (list_Links_vs_Route_direction msg))
    (cl:cons ':LIST_LINKS_SIZE (LIST_LINKS_SIZE msg))
    (cl:cons ':NBRE_POINT_CIRCUIT_GPS (NBRE_POINT_CIRCUIT_GPS msg))
    (cl:cons ':NBRE_POINT_TABLEAU_GPS (NBRE_POINT_TABLEAU_GPS msg))
    (cl:cons ':Tableau_circuit_GPS (Tableau_circuit_GPS msg))
    (cl:cons ':Tableau_circuit_GPS_gauche (Tableau_circuit_GPS_gauche msg))
    (cl:cons ':Tableau_circuit_GPS_droite (Tableau_circuit_GPS_droite msg))
    (cl:cons ':Tableau_circuit_GPS_MEgauche (Tableau_circuit_GPS_MEgauche msg))
    (cl:cons ':Tableau_circuit_GPS_MEdroite (Tableau_circuit_GPS_MEdroite msg))
    (cl:cons ':Tableau_circuit_speedlimit (Tableau_circuit_speedlimit msg))
    (cl:cons ':Tableau_circuit_curvature (Tableau_circuit_curvature msg))
    (cl:cons ':Tableau_circuit_trafficsign (Tableau_circuit_trafficsign msg))
    (cl:cons ':Tableau_circuit_ehSegmentAO (Tableau_circuit_ehSegmentAO msg))
    (cl:cons ':Tableau_circuit_ehSegmentEO (Tableau_circuit_ehSegmentEO msg))
))
