image: ros:kinetic-robot

variables:
  USE_ROSDEP: "true"

before_script:
 - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
 - source ros_gitlab_ci/gitlab-ci.bash

cache:
  paths:
    - ccache/

# catkin_make
catkin_make:
  stage: build
  script:
    - catkin_make

# catkin tools
catkin tools:
  stage: build
  script:
    - catkin build --summarize --no-status --force-color
