// Generated by gencpp from file message_project_s/ObstacleAlignment.msg
// DO NOT EDIT!


#ifndef MESSAGE_PROJECT_S_MESSAGE_OBSTACLEALIGNMENT_H
#define MESSAGE_PROJECT_S_MESSAGE_OBSTACLEALIGNMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/UInt8.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Accel.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Vector3.h>
#include <std_msgs/Float32.h>
#include <std_msgs/UInt8.h>
#include <std_msgs/Float64.h>

namespace message_project_s
{
template <class ContainerAllocator>
struct ObstacleAlignment_
{
  typedef ObstacleAlignment_<ContainerAllocator> Type;

  ObstacleAlignment_()
    : header()
    , id()
    , obstaclePosition()
    , obstacleVelocity()
    , obstacleAcceleration()
    , obstaclePoseVariance()
    , obstacleVelocityVariance()
    , obstacleDimensions()
    , groundHeight()
    , obstacleClass(0)
    , vision_only_sign_type(0)
    , classificationProbability()
    , dateAcquisition()  {
    }
  ObstacleAlignment_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(_alloc)
    , obstaclePosition(_alloc)
    , obstacleVelocity(_alloc)
    , obstacleAcceleration(_alloc)
    , obstaclePoseVariance(_alloc)
    , obstacleVelocityVariance(_alloc)
    , obstacleDimensions(_alloc)
    , groundHeight(_alloc)
    , obstacleClass(0)
    , vision_only_sign_type(0)
    , classificationProbability(_alloc)
    , dateAcquisition(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _obstaclePosition_type;
  _obstaclePosition_type obstaclePosition;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _obstacleVelocity_type;
  _obstacleVelocity_type obstacleVelocity;

   typedef  ::geometry_msgs::Accel_<ContainerAllocator>  _obstacleAcceleration_type;
  _obstacleAcceleration_type obstacleAcceleration;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _obstaclePoseVariance_type;
  _obstaclePoseVariance_type obstaclePoseVariance;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _obstacleVelocityVariance_type;
  _obstacleVelocityVariance_type obstacleVelocityVariance;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _obstacleDimensions_type;
  _obstacleDimensions_type obstacleDimensions;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _groundHeight_type;
  _groundHeight_type groundHeight;

   typedef uint8_t _obstacleClass_type;
  _obstacleClass_type obstacleClass;

   typedef uint8_t _vision_only_sign_type_type;
  _vision_only_sign_type_type vision_only_sign_type;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _classificationProbability_type;
  _classificationProbability_type classificationProbability;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _dateAcquisition_type;
  _dateAcquisition_type dateAcquisition;





  typedef boost::shared_ptr< ::message_project_s::ObstacleAlignment_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::message_project_s::ObstacleAlignment_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleAlignment_

typedef ::message_project_s::ObstacleAlignment_<std::allocator<void> > ObstacleAlignment;

typedef boost::shared_ptr< ::message_project_s::ObstacleAlignment > ObstacleAlignmentPtr;
typedef boost::shared_ptr< ::message_project_s::ObstacleAlignment const> ObstacleAlignmentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::message_project_s::ObstacleAlignment_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::message_project_s::ObstacleAlignment_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace message_project_s

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'delphi_srr_msgs': ['/home/dev/as_drivers_customer/install/share/delphi_srr_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'delphi_esr_msgs': ['/home/dev/as_drivers_customer/install/share/delphi_esr_msgs/cmake/../msg'], 'message_project_s': ['/home/segula/Desktop/ava/achitecture_ws/src/smart_sensor/message_project_s/msg'], 'radar_msgs': ['/home/dev/as_drivers_customer/install/share/radar_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mobileye_560_660_msgs': ['/home/dev/as_drivers_customer/install/share/mobileye_560_660_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::message_project_s::ObstacleAlignment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_project_s::ObstacleAlignment_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message_project_s::ObstacleAlignment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message_project_s::ObstacleAlignment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_project_s::ObstacleAlignment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_project_s::ObstacleAlignment_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::message_project_s::ObstacleAlignment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dce63e168b330791d863e425f8e25292";
  }

  static const char* value(const ::message_project_s::ObstacleAlignment_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdce63e168b330791ULL;
  static const uint64_t static_value2 = 0xd863e425f8e25292ULL;
};

template<class ContainerAllocator>
struct DataType< ::message_project_s::ObstacleAlignment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message_project_s/ObstacleAlignment";
  }

  static const char* value(const ::message_project_s::ObstacleAlignment_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::message_project_s::ObstacleAlignment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
std_msgs/UInt8 id\n\
\n\
geometry_msgs/Pose obstaclePosition		# obstacle position\n\
geometry_msgs/Twist obstacleVelocity		# obstacle speed\n\
geometry_msgs/Accel obstacleAcceleration	# obstacle acceleration\n\
geometry_msgs/Pose obstaclePoseVariance		# obstacle position variance\n\
geometry_msgs/Twist obstacleVelocityVariance	# obstacle speed variance\n\
geometry_msgs/Vector3 obstacleDimensions	# obstacle x,y,z - length, width, height\n\
std_msgs/Float32 groundHeight			# ground height\n\
uint8 obstacleClass\n\
uint8 vision_only_sign_type\n\
std_msgs/UInt8 classificationProbability\n\
std_msgs/Float64 dateAcquisition\n\
\n\
# History\n\
\n\
\n\
\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/UInt8\n\
uint8 data\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Accel\n\
# This expresses acceleration in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
================================================================================\n\
MSG: std_msgs/Float64\n\
float64 data\n\
";
  }

  static const char* value(const ::message_project_s::ObstacleAlignment_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::message_project_s::ObstacleAlignment_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.obstaclePosition);
      stream.next(m.obstacleVelocity);
      stream.next(m.obstacleAcceleration);
      stream.next(m.obstaclePoseVariance);
      stream.next(m.obstacleVelocityVariance);
      stream.next(m.obstacleDimensions);
      stream.next(m.groundHeight);
      stream.next(m.obstacleClass);
      stream.next(m.vision_only_sign_type);
      stream.next(m.classificationProbability);
      stream.next(m.dateAcquisition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleAlignment_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::message_project_s::ObstacleAlignment_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::message_project_s::ObstacleAlignment_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.id);
    s << indent << "obstaclePosition: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.obstaclePosition);
    s << indent << "obstacleVelocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.obstacleVelocity);
    s << indent << "obstacleAcceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Accel_<ContainerAllocator> >::stream(s, indent + "  ", v.obstacleAcceleration);
    s << indent << "obstaclePoseVariance: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.obstaclePoseVariance);
    s << indent << "obstacleVelocityVariance: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.obstacleVelocityVariance);
    s << indent << "obstacleDimensions: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.obstacleDimensions);
    s << indent << "groundHeight: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.groundHeight);
    s << indent << "obstacleClass: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.obstacleClass);
    s << indent << "vision_only_sign_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vision_only_sign_type);
    s << indent << "classificationProbability: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.classificationProbability);
    s << indent << "dateAcquisition: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.dateAcquisition);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_PROJECT_S_MESSAGE_OBSTACLEALIGNMENT_H
