// Generated by gencpp from file message_project_s/sync.msg
// DO NOT EDIT!


#ifndef MESSAGE_PROJECT_S_MESSAGE_SYNC_H
#define MESSAGE_PROJECT_S_MESSAGE_SYNC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/UInt8.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Twist.h>
#include <geometry_msgs/Accel.h>

namespace message_project_s
{
template <class ContainerAllocator>
struct sync_
{
  typedef sync_<ContainerAllocator> Type;

  sync_()
    : header()
    , id()
    , obstaclePosition()
    , obstacleVelocity()
    , obstacleAcceleration()
    , trkID(0)
    , trkLatrate(0.0)
    , trkAngle(0.0)
    , trkRange(0.0)
    , trkWidth(0.0)
    , trkRangeaccel(0.0)
    , trkRangerate(0.0)  {
    }
  sync_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(_alloc)
    , obstaclePosition(_alloc)
    , obstacleVelocity(_alloc)
    , obstacleAcceleration(_alloc)
    , trkID(0)
    , trkLatrate(0.0)
    , trkAngle(0.0)
    , trkRange(0.0)
    , trkWidth(0.0)
    , trkRangeaccel(0.0)
    , trkRangerate(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::std_msgs::UInt8_<ContainerAllocator>  _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _obstaclePosition_type;
  _obstaclePosition_type obstaclePosition;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _obstacleVelocity_type;
  _obstacleVelocity_type obstacleVelocity;

   typedef  ::geometry_msgs::Accel_<ContainerAllocator>  _obstacleAcceleration_type;
  _obstacleAcceleration_type obstacleAcceleration;

   typedef uint8_t _trkID_type;
  _trkID_type trkID;

   typedef float _trkLatrate_type;
  _trkLatrate_type trkLatrate;

   typedef float _trkAngle_type;
  _trkAngle_type trkAngle;

   typedef float _trkRange_type;
  _trkRange_type trkRange;

   typedef float _trkWidth_type;
  _trkWidth_type trkWidth;

   typedef float _trkRangeaccel_type;
  _trkRangeaccel_type trkRangeaccel;

   typedef float _trkRangerate_type;
  _trkRangerate_type trkRangerate;





  typedef boost::shared_ptr< ::message_project_s::sync_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::message_project_s::sync_<ContainerAllocator> const> ConstPtr;

}; // struct sync_

typedef ::message_project_s::sync_<std::allocator<void> > sync;

typedef boost::shared_ptr< ::message_project_s::sync > syncPtr;
typedef boost::shared_ptr< ::message_project_s::sync const> syncConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::message_project_s::sync_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::message_project_s::sync_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace message_project_s

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'delphi_srr_msgs': ['/home/dev/as_drivers_customer/install/share/delphi_srr_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'delphi_esr_msgs': ['/home/dev/as_drivers_customer/install/share/delphi_esr_msgs/cmake/../msg'], 'message_project_s': ['/home/segula/Desktop/ava/achitecture_ws/src/smart_sensor/message_project_s/msg'], 'radar_msgs': ['/home/dev/as_drivers_customer/install/share/radar_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'mobileye_560_660_msgs': ['/home/dev/as_drivers_customer/install/share/mobileye_560_660_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::message_project_s::sync_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::message_project_s::sync_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message_project_s::sync_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::message_project_s::sync_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_project_s::sync_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::message_project_s::sync_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::message_project_s::sync_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8362c306ad17d94fd3f60283bbd12b35";
  }

  static const char* value(const ::message_project_s::sync_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8362c306ad17d94fULL;
  static const uint64_t static_value2 = 0xd3f60283bbd12b35ULL;
};

template<class ContainerAllocator>
struct DataType< ::message_project_s::sync_<ContainerAllocator> >
{
  static const char* value()
  {
    return "message_project_s/sync";
  }

  static const char* value(const ::message_project_s::sync_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::message_project_s::sync_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
std_msgs/UInt8 id\n\
\n\
geometry_msgs/Pose obstaclePosition		# obstacle position\n\
geometry_msgs/Twist obstacleVelocity		# obstacle speed\n\
geometry_msgs/Accel obstacleAcceleration	# obstacle acceleration\n\
uint8 trkID\n\
float32 trkLatrate\n\
float32 trkAngle\n\
float32 trkRange\n\
float32 trkWidth\n\
float32 trkRangeaccel\n\
float32 trkRangerate  \n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/UInt8\n\
uint8 data\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Accel\n\
# This expresses acceleration in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
";
  }

  static const char* value(const ::message_project_s::sync_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::message_project_s::sync_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.obstaclePosition);
      stream.next(m.obstacleVelocity);
      stream.next(m.obstacleAcceleration);
      stream.next(m.trkID);
      stream.next(m.trkLatrate);
      stream.next(m.trkAngle);
      stream.next(m.trkRange);
      stream.next(m.trkWidth);
      stream.next(m.trkRangeaccel);
      stream.next(m.trkRangerate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sync_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::message_project_s::sync_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::message_project_s::sync_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8_<ContainerAllocator> >::stream(s, indent + "  ", v.id);
    s << indent << "obstaclePosition: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.obstaclePosition);
    s << indent << "obstacleVelocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.obstacleVelocity);
    s << indent << "obstacleAcceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Accel_<ContainerAllocator> >::stream(s, indent + "  ", v.obstacleAcceleration);
    s << indent << "trkID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.trkID);
    s << indent << "trkLatrate: ";
    Printer<float>::stream(s, indent + "  ", v.trkLatrate);
    s << indent << "trkAngle: ";
    Printer<float>::stream(s, indent + "  ", v.trkAngle);
    s << indent << "trkRange: ";
    Printer<float>::stream(s, indent + "  ", v.trkRange);
    s << indent << "trkWidth: ";
    Printer<float>::stream(s, indent + "  ", v.trkWidth);
    s << indent << "trkRangeaccel: ";
    Printer<float>::stream(s, indent + "  ", v.trkRangeaccel);
    s << indent << "trkRangerate: ";
    Printer<float>::stream(s, indent + "  ", v.trkRangerate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGE_PROJECT_S_MESSAGE_SYNC_H
